/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package officequanlisinhvien;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MANH TRUONG
 */
public class hocbont extends javax.swing.JPanel {

    DefaultTableModel tblModel;

    /**
     * Creates new form hocbont
     */
    public hocbont() {
        initComponents();
        innitTable();
        loaddulieu();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        l = new javax.swing.JScrollPane();
        bangketqua = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        diemso = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtKetqua = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btntrungbinh = new javax.swing.JButton();
        lblthongbao = new javax.swing.JLabel();
        gpa = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnLoa = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtdiemchuyencan = new javax.swing.JTextField();
        txtdiemgiuaki = new javax.swing.JTextField();
        txtdiemcuoikif = new javax.swing.JTextField();
        txtmasv = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("DANH SÁCH TÍNH ĐIỂM");

        l.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lMouseClicked(evt);
            }
        });

        bangketqua.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        bangketqua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bangketquaMouseClicked(evt);
            }
        });
        l.setViewportView(bangketqua);

        jPanel1.setBackground(new java.awt.Color(255, 102, 51));

        diemso.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        diemso.setForeground(new java.awt.Color(51, 51, 255));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 255));
        jLabel8.setText("Điểm số hệ 4");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 255));
        jLabel9.setText("Điểm chữ ");

        txtKetqua.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtKetqua.setForeground(new java.awt.Color(51, 51, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 255));
        jLabel7.setText("kết quả trung bình hệ 10  ");

        btntrungbinh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btntrungbinh.setForeground(new java.awt.Color(51, 51, 255));
        btntrungbinh.setText("tính điểm trung bình  ");
        btntrungbinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntrungbinhActionPerformed(evt);
            }
        });

        lblthongbao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblthongbao.setForeground(new java.awt.Color(51, 51, 255));

        gpa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        gpa.setForeground(new java.awt.Color(51, 51, 255));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 255));
        jLabel10.setText("Đánh Giá");

        btnLoa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLoa.setForeground(new java.awt.Color(0, 0, 255));
        btnLoa.setText("RESET");
        btnLoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtKetqua, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(btntrungbinh, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(diemso, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnLoa, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(gpa, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(lblthongbao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(gpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(diemso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntrungbinh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblthongbao, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtKetqua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(27, 27, 27)
                .addComponent(btnLoa)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 102, 51));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("Điểm giữa kì ");

        txtdiemchuyencan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtdiemchuyencan.setForeground(new java.awt.Color(51, 51, 255));

        txtdiemgiuaki.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtdiemgiuaki.setForeground(new java.awt.Color(51, 51, 255));

        txtdiemcuoikif.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtdiemcuoikif.setForeground(new java.awt.Color(51, 51, 255));

        txtmasv.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtmasv.setForeground(new java.awt.Color(51, 51, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("Điểm cuối kì ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Mã sinh viên ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("Điểm chuyên cần ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtdiemchuyencan, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(txtmasv)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtdiemcuoikif, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdiemgiuaki, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 96, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtmasv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtdiemchuyencan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtdiemgiuaki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtdiemcuoikif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(l, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1057, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(377, 377, 377)
                                .addComponent(jLabel1)))
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(l, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lMouseClicked

    }//GEN-LAST:event_lMouseClicked

    private void bangketquaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bangketquaMouseClicked
        int row = bangketqua.getSelectedRow();

        if (row >= 0) {
            txtmasv.setText(bangketqua.getValueAt(row, 0).toString());
            txtdiemchuyencan.setText(bangketqua.getValueAt(row, 2).toString());
            txtdiemgiuaki.setText(bangketqua.getValueAt(row, 3).toString());
            txtdiemcuoikif.setText(bangketqua.getValueAt(row, 4).toString());
        }

        //       double ketqua = s1*0.1 + s2*0.2 + s3*0.7;
        try {
            double s1 = Double.parseDouble(txtdiemchuyencan.getText());
            double s2 = Double.parseDouble(txtdiemgiuaki.getText());

            double s3 = Double.parseDouble(txtdiemcuoikif.getText());
            double ketqua = s1 * 0.1 + s2 * 0.2 + s3 * 0.7;
//            String s = String.valueOf(ketqua);

//            if (s1 < 5 || s2 < 6 || s3 < 5) {
////                JOptionPane.showMessageDialog(this, "fail");
////                  gpa.setText("trượt");
//            } else {
////                JOptionPane.showMessageDialog(this, "qua môn");
////                gpa.setText("qua");
//            }
            txtKetqua.setText("" + ketqua);
            if (ketqua < 4) {
                gpa.setText("F");
                diemso.setText("0");
                lblthongbao.setText("không đạt");
            } else if (ketqua >= 4.0 && ketqua < 4.9) {
                gpa.setText("D");
                diemso.setText("1.0");
                lblthongbao.setText("Đạt");
            } else if (ketqua >= 5.0 && ketqua < 5.4) {
                gpa.setText("D+");
                diemso.setText("1.5");
                lblthongbao.setText("Đạt");
            } else if (ketqua >= 5.5 && ketqua < 6.4) {
                gpa.setText("C");
                diemso.setText("2.0");
                lblthongbao.setText("Đạt");
            } else if (ketqua >= 6.5 && ketqua < 6.9) {
                gpa.setText("C");
                diemso.setText("2.5");
                lblthongbao.setText("Đạt");
            } else if (ketqua >= 7.0 && ketqua < 7.9) {
                gpa.setText("B");
                diemso.setText("3.0");
                lblthongbao.setText("Đạt");
            } else if (ketqua >= 8.0 && ketqua < 8.4) {
                gpa.setText("B+");
                diemso.setText("3.5");
                lblthongbao.setText("Đạt");
            } else if (ketqua >= 8.5 && ketqua < 8.9) {
                gpa.setText("A");
                diemso.setText("3.7");
                lblthongbao.setText("Đạt");
            } else {
                gpa.setText("A+");
                diemso.setText("4.0");
                lblthongbao.setText("Đạt");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }      
    }//GEN-LAST:event_bangketquaMouseClicked

    private void btntrungbinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntrungbinhActionPerformed
//       double ketqua = s1*0.1 + s2*0.2 + s3*0.7;
        try {
            double s1 = Double.parseDouble(txtdiemchuyencan.getText());
            double s2 = Double.parseDouble(txtdiemgiuaki.getText());

            double s3 = Double.parseDouble(txtdiemcuoikif.getText());
            double ketqua =(double) s1 * 0.1 + s2 * 0.2 + s3 * 0.7;
//            String s = String.valueOf(ketqua);

//            if (s1 < 5 || s2 < 6 || s3 < 5) {
////                JOptionPane.showMessageDialog(this, "fail");
////                  gpa.setText("trượt");
//            } else {
////                JOptionPane.showMessageDialog(this, "qua môn");
////                gpa.setText("qua");
//            }
            txtKetqua.setText("" + ketqua);
            if (ketqua < 4) {
                gpa.setText("F");
                diemso.setText("0");
                lblthongbao.setText("Không đạt");
            } else if (ketqua >= 4.0 && ketqua < 4.9) {
                gpa.setText("D");
                diemso.setText("1.0");
                lblthongbao.setText("Đạt");
            } else if (ketqua >= 5.0 && ketqua < 5.4) {
                gpa.setText("D+");
                diemso.setText("1.5");
                lblthongbao.setText("Đạt");
            } else if (ketqua >= 5.5 && ketqua < 6.4) {
                gpa.setText("C");
                diemso.setText("2.0");
                lblthongbao.setText("Đạt");
            } else if (ketqua >= 6.5 && ketqua < 6.9) {
                gpa.setText("C");
                diemso.setText("2.5");
                lblthongbao.setText("Đạt");
            } else if (ketqua >= 7.0 && ketqua < 7.9) {
                gpa.setText("B");
                diemso.setText("3.0");
                lblthongbao.setText("Đạt");
            } else if (ketqua >= 8.0 && ketqua < 8.4) {
                gpa.setText("B+");
                diemso.setText("3.5");
                lblthongbao.setText("Đạt");
            } else if (ketqua >= 8.5 && ketqua < 8.9) {
                gpa.setText("A");
                diemso.setText("3.7");
                lblthongbao.setText("Đạt");
            } else {
                gpa.setText("A+");
                diemso.setText("4.0");
                lblthongbao.setText("Đạt");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btntrungbinhActionPerformed

    private void btnLoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoaActionPerformed
        loaddulieu();
    }//GEN-LAST:event_btnLoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bangketqua;
    private javax.swing.JButton btnLoa;
    private javax.swing.JButton btntrungbinh;
    private javax.swing.JTextField diemso;
    private javax.swing.JTextField gpa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JScrollPane l;
    private javax.swing.JLabel lblthongbao;
    private javax.swing.JTextField txtKetqua;
    private javax.swing.JTextField txtdiemchuyencan;
    private javax.swing.JTextField txtdiemcuoikif;
    private javax.swing.JTextField txtdiemgiuaki;
    private javax.swing.JTextField txtmasv;
    // End of variables declaration//GEN-END:variables

    private void innitTable() {
//        tblModel = new DefaultTableModel();
//        tblModel.setColumnIdentifiers(new String[]{"Mã sv", "Mã môn", "diểm chuyên cần", "điểm giữa kì", "điểm thi cuối kì ", "điểm thi lại "});//thiết lập tên của của các table
//        bangketqua.se
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(new String[]{"Mã sv", "Mã môn", "diểm chuyên cần", "điểm giữa kì", "điểm thi cuối kì ", "điểm thi lại "});
        bangketqua.setModel(tblModel);
    }

    private void loaddulieu() {
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=quanlysinhvien";
            String username = "sa";
            String password = "123456789";
            Connection con = DriverManager.getConnection(url, username, password);
            String sql1 = "select*from ketqua";
            PreparedStatement ps1 = con.prepareStatement(sql1);
            ResultSet rs1 = ps1.executeQuery();//trả về kết quả ResultSet
            tblModel.setRowCount(0);
            while (rs1.next()) {
                String[] row = new String[]{
                    rs1.getString("masv"), rs1.getString("mamon"), rs1.getString("diemhs1"), rs1.getString("diemhs2"), rs1.getString("diemthi"), rs1.getString("diemthilai")
                };
                tblModel.addRow(row);
            }
            tblModel.fireTableDataChanged();//cập nhật dữ liệu trong bảng
            rs1.close();
            ps1.close();
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
