/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package officequanlisinhvien;

import java.awt.Color;
import java.awt.Component;
import java.awt.Component;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author MANH TRUONG
 */
public class QLSV extends javax.swing.JFrame {

    /**
     * Creates new form QLSV
     */
    public QLSV() {
        initComponents();
        setLocationRelativeTo(null);
        //setExtendedState(getExtendedState() | QLSV.MAXIMIZED_BOTH);//phóng to 
//        formdk dialog=new formdk(this, true);
//        dk.setVisible(true);gọi form đăng nhập lên trước
    }
//    quanlykhoahoc khoahoc;
//    quanlylophoc lophoc;
//    quanlymonhoc monhoc;
//    quanlychuyennganh chuyennganh;
//    quanlyketqua ketqua;
//    quanlysinhvien sinhvien;
//    hocbont hocbong;
// 

    private void ButtonClose(String title) {
        int index = jTabbedPane1.indexOfTab(title);
        JPanel pnlTab = new JPanel(new GridBagLayout());
        pnlTab.setOpaque(false);
        JLabel lblTitle = new JLabel(title);
        JButton btnClose = new JButton("x");

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1;

        pnlTab.add(lblTitle, gbc);

        gbc.gridx++;
        gbc.weightx = 0;

        pnlTab.add(btnClose, gbc);

        jTabbedPane1.setTabComponentAt(index, pnlTab);
        btnClose.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Component selected = jTabbedPane1.getSelectedComponent();
                if (selected != null) {
                    jTabbedPane1.remove(selected);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        btnChuyenNganh = new javax.swing.JButton();
        btnKetQua = new javax.swing.JButton();
        btnLopHoc = new javax.swing.JButton();
        btnMonHoc = new javax.swing.JButton();
        btnsinhVien = new javax.swing.JButton();
        btnKhoaHoc = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuDangxuat = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuQuanLysinhvien = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        btnQuanlyketqua = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        menuquanlylophoc = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        btnquanlymonhoc = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        btnquanlychuyennganh = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        btnquanlykhoahoc = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("jMenu3");

        jMenuItem10.setText("jMenuItem10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnChuyenNganh.setBackground(new java.awt.Color(102, 255, 102));
        btnChuyenNganh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnChuyenNganh.setForeground(new java.awt.Color(51, 51, 255));
        btnChuyenNganh.setText("Quản Lý Chuyên Ngành");
        btnChuyenNganh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyenNganhActionPerformed(evt);
            }
        });

        btnKetQua.setBackground(new java.awt.Color(102, 255, 102));
        btnKetQua.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnKetQua.setForeground(new java.awt.Color(51, 51, 255));
        btnKetQua.setText("Bảng Kết Quả Học Tập ");
        btnKetQua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKetQuaActionPerformed(evt);
            }
        });

        btnLopHoc.setBackground(new java.awt.Color(102, 255, 102));
        btnLopHoc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLopHoc.setForeground(new java.awt.Color(51, 51, 255));
        btnLopHoc.setText("Quản Lý Lớp Học ");
        btnLopHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLopHocActionPerformed(evt);
            }
        });

        btnMonHoc.setBackground(new java.awt.Color(102, 255, 102));
        btnMonHoc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMonHoc.setForeground(new java.awt.Color(51, 51, 255));
        btnMonHoc.setText("Quản Lý Môn Học ");
        btnMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonHocActionPerformed(evt);
            }
        });

        btnsinhVien.setBackground(new java.awt.Color(102, 255, 102));
        btnsinhVien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnsinhVien.setForeground(new java.awt.Color(51, 51, 255));
        btnsinhVien.setText("Quản Lý Sinh Viên");
        btnsinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsinhVienActionPerformed(evt);
            }
        });

        btnKhoaHoc.setBackground(new java.awt.Color(102, 255, 102));
        btnKhoaHoc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnKhoaHoc.setForeground(new java.awt.Color(51, 51, 255));
        btnKhoaHoc.setText("Quản Lý Khóa Học ");
        btnKhoaHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoaHocActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(102, 255, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 255));
        jButton1.setText("Điểm GPA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLopHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKetQua, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                        .addComponent(btnKhoaHoc, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                        .addComponent(btnsinhVien, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                        .addComponent(btnMonHoc, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                        .addComponent(btnChuyenNganh, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(btnChuyenNganh, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnLopHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btnsinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(btnKhoaHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnKetQua, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        jScrollPane1.setBackground(new java.awt.Color(255, 102, 51));

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(jTabbedPane1);

        jMenu1.setText("Hệ Thống");

        menuDangxuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        menuDangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Login-icon-16.png"))); // NOI18N
        menuDangxuat.setText("Đăng xuất");
        menuDangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDangxuatActionPerformed(evt);
            }
        });
        jMenu1.add(menuDangxuat);
        jMenu1.add(jSeparator2);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Button-Close-icon-16.png"))); // NOI18N
        jMenuItem4.setText("Thoát");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản Lý");

        menuQuanLysinhvien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        menuQuanLysinhvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/10207-man-student-light-skin-tone-icon-16.png"))); // NOI18N
        menuQuanLysinhvien.setText("Quản Lý Sinh Viên");
        menuQuanLysinhvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuanLysinhvienActionPerformed(evt);
            }
        });
        jMenu2.add(menuQuanLysinhvien);
        jMenu2.add(jSeparator1);

        btnQuanlyketqua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gpa-icon.png"))); // NOI18N
        btnQuanlyketqua.setText("Quản Lý Kết Quả");
        btnQuanlyketqua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanlyketquaActionPerformed(evt);
            }
        });
        jMenu2.add(btnQuanlyketqua);
        jMenu2.add(jSeparator4);

        menuquanlylophoc.setText("Quản Lý Lớp Học");
        menuquanlylophoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuquanlylophocActionPerformed(evt);
            }
        });
        jMenu2.add(menuquanlylophoc);
        jMenu2.add(jSeparator5);

        btnquanlymonhoc.setText("Quản Lý Môn Học");
        btnquanlymonhoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquanlymonhocActionPerformed(evt);
            }
        });
        jMenu2.add(btnquanlymonhoc);
        jMenu2.add(jSeparator6);

        btnquanlychuyennganh.setText("Quản Lý Chuyên Ngành");
        btnquanlychuyennganh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquanlychuyennganhActionPerformed(evt);
            }
        });
        jMenu2.add(btnquanlychuyennganh);
        jMenu2.add(jSeparator7);

        btnquanlykhoahoc.setText("Quản Lý Khóa Học");
        btnquanlykhoahoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquanlykhoahocActionPerformed(evt);
            }
        });
        jMenu2.add(btnquanlykhoahoc);
        jMenu2.add(jSeparator8);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Danh Sách Học Bổng");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Trợ Giúp");

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Actions-help-about-icon-16.png"))); // NOI18N
        jMenuItem6.setText("Nội Dung");
        jMenu4.add(jMenuItem6);
        jMenu4.add(jSeparator3);

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Help-icon-16.png"))); // NOI18N
        jMenuItem7.setText("Giới Thiệu");
        jMenu4.add(jMenuItem7);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void menuQuanLysinhvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuanLysinhvienActionPerformed
//        if (sinhvien == null) {
//            sinhvien = new quanlysinhvien();
//            jTabbedPane1.addTab("quản lý sinh viên", sinhvien);
//        }
//        jTabbedPane1.setSelectedComponent(sinhvien);
        if (jTabbedPane1.indexOfTab("quản lý sinh viên") <= -1) {
            jTabbedPane1.add("quản lý sinh viên ", new quanlysinhvien());
            ButtonClose("quản lý sinh viên ");
            jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfTab("quản lý sinh viên "));
        } else {
            jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfTab("quản lý sinh viên "));
            JOptionPane.showMessageDialog(this, "Mục này đang được mở ");
        }
    }//GEN-LAST:event_menuQuanLysinhvienActionPerformed

    private void btnChuyenNganhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyenNganhActionPerformed
//        if (chuyennganh == null) {
//            chuyennganh = new quanlychuyennganh();
//            jTabbedPane1.addTab("quản lý chuyên ngành", chuyennganh);
//        }
//        jTabbedPane1.setSelectedComponent(chuyennganh);
//        btnChuyenNganh.setForeground(Color.red);
        btnChuyenNganh.setForeground(Color.red);
        this.setForeground(Color.blue);
        if (jTabbedPane1.indexOfTab("quản lý chuyên ngành") <= -1) {
            jTabbedPane1.add("quản lý chuyên ngành ", new quanlychuyennganh());
            ButtonClose("quản lý chuyên ngành ");
            jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfTab("quản lý chuyên ngành "));
        } else {
            jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfTab("quản lý chuyên ngành "));
            JOptionPane.showMessageDialog(this, "Mục này đang được mở ");
           
        }
    }//GEN-LAST:event_btnChuyenNganhActionPerformed

    private void btnKhoaHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoaHocActionPerformed
//        if (khoahoc == null) {
//            khoahoc = new quanlykhoahoc();
//            jTabbedPane1.addTab("quản lý khóa học", khoahoc);
//        }
//        jTabbedPane1.setSelectedComponent(khoahoc);
        if (jTabbedPane1.indexOfTab("quản lý khóa học") <= -1) {
            jTabbedPane1.add("quản lý khóa học ", new quanlykhoahoc());
            ButtonClose("quản lý khóa học ");
            jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfTab("quản lý khóa học "));
        } else {
            jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfTab("quản lý khóa học "));
            JOptionPane.showMessageDialog(this, "Mục này đang được mở ");
        }
    }//GEN-LAST:event_btnKhoaHocActionPerformed

    private void menuquanlylophocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuquanlylophocActionPerformed
//        if (lophoc == null) {
//            lophoc = new quanlylophoc();
//            jTabbedPane1.addTab("quản lý lớp", lophoc);
//        }
//        jTabbedPane1.setSelectedComponent(lophoc);
        if (jTabbedPane1.indexOfTab("quản lý lớp") <= -1) {
            jTabbedPane1.add("quản lý lớp ", new quanlylophoc());
            ButtonClose("quản lý lớp ");
            jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfTab("quản lý lớp "));
        } else {
            jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfTab("quản lý lớp "));
            JOptionPane.showMessageDialog(this, "Mục này đang được mở ");
        }
    }//GEN-LAST:event_menuquanlylophocActionPerformed

    private void btnQuanlyketquaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanlyketquaActionPerformed
//        if (ketqua == null) {
//            ketqua = new quanlyketqua();
//            jTabbedPane1.addTab("quản lý kết quả", ketqua);
//        }
//        jTabbedPane1.setSelectedComponent(ketqua);
        if (jTabbedPane1.indexOfTab("quản lý kết quả ") <= -1) {
            jTabbedPane1.add("quản lý kết quả ", new quanlyketqua());
            ButtonClose("quản lý kết quả ");
            jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfTab("quản lý kết quả "));
        } else {
            jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfTab("quản lý kết quả"));
            JOptionPane.showMessageDialog(this, "Mục này đang được mở ");
        }
    }//GEN-LAST:event_btnQuanlyketquaActionPerformed

    private void btnLopHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLopHocActionPerformed
        menuquanlylophocActionPerformed(evt);
    }//GEN-LAST:event_btnLopHocActionPerformed

    private void btnquanlykhoahocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquanlykhoahocActionPerformed
        btnKhoaHocActionPerformed(evt);
    }//GEN-LAST:event_btnquanlykhoahocActionPerformed

    private void btnquanlymonhocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquanlymonhocActionPerformed
//        if (monhoc == null) {
//            monhoc = new quanlymonhoc();
//            jTabbedPane1.addTab("quản lý môn học", monhoc);
//        }
//        jTabbedPane1.setSelectedComponent(monhoc);
        if (jTabbedPane1.indexOfTab("quản lý môn học") <= -1) {
            jTabbedPane1.add("quản lý môn học ", new quanlymonhoc());
            ButtonClose("quản lý môn học ");
            jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfTab("quản lý môn học "));
        } else {
            jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfTab("quản lý môn học "));
            JOptionPane.showMessageDialog(this, "Mục này đang được mở ");
        }
    }//GEN-LAST:event_btnquanlymonhocActionPerformed

    private void btnMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonHocActionPerformed
        btnquanlymonhocActionPerformed(evt);
    }//GEN-LAST:event_btnMonHocActionPerformed

    private void btnsinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsinhVienActionPerformed
        menuQuanLysinhvienActionPerformed(evt);
    }//GEN-LAST:event_btnsinhVienActionPerformed

    private void btnKetQuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKetQuaActionPerformed
        btnQuanlyketquaActionPerformed(evt);
        btnKetQua.setForeground(Color.red);
        this.setForeground(Color.blue);

    }//GEN-LAST:event_btnKetQuaActionPerformed

    private void btnquanlychuyennganhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquanlychuyennganhActionPerformed
        btnChuyenNganhActionPerformed(evt);
    }//GEN-LAST:event_btnquanlychuyennganhActionPerformed

    private void menuDangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDangxuatActionPerformed
        formdk dk = new formdk();
        dk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuDangxuatActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
//        if (hocbong == null) {
//            hocbong = new hocbont();
//            jTabbedPane1.addTab("danh sách học bổng", hocbong);
//        }
//        jTabbedPane1.setSelectedComponent(hocbong);
        if (jTabbedPane1.indexOfTab("tính điểm ") <= -1) {
            jTabbedPane1.add("tính điểm ", new hocbont());
            ButtonClose("tính điểm ");
            jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfTab("tính điểm "));
        } else {
            jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfTab("tính điểm "));
            JOptionPane.showMessageDialog(this, "Mục này đang được mở ");
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jMenuItem2ActionPerformed(evt);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLSV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChuyenNganh;
    private javax.swing.JButton btnKetQua;
    private javax.swing.JButton btnKhoaHoc;
    private javax.swing.JButton btnLopHoc;
    private javax.swing.JButton btnMonHoc;
    private javax.swing.JMenuItem btnQuanlyketqua;
    private javax.swing.JMenuItem btnquanlychuyennganh;
    private javax.swing.JMenuItem btnquanlykhoahoc;
    private javax.swing.JMenuItem btnquanlymonhoc;
    private javax.swing.JButton btnsinhVien;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem menuDangxuat;
    private javax.swing.JMenuItem menuQuanLysinhvien;
    private javax.swing.JMenuItem menuquanlylophoc;
    // End of variables declaration//GEN-END:variables
}
