/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package officequanlisinhvien;

import java.awt.Color;
import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MANH TRUONG
 */
public class quanlylophoc extends javax.swing.JPanel {

    DefaultTableModel tblModel;//định nghĩa đối tượng tblModel 

    /**
     * Creates new form quanlylophoc
     */
    public quanlylophoc() {
        initComponents();
        initTable();
        ComboBox();
        loadDuLieu();

    }

    private Boolean ktTrungThem(String manhap) {
        try {
            int row = 0;
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=quanlysinhvien";
            String username = "sa";
            String password = "123456789";

            Connection con = DriverManager.getConnection(url, username, password);
            String sql = "Select * from lop where malop=N'" + manhap + "'";
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();//trả về kết quả ResultSet
            tblModel.setRowCount(0);
            while (rs.next()) {
                row++;
            }
            if (row > 0) {
                return true;
            } else {
                return false;
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGhi = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cboKhoa = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldulieu = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMalop = new javax.swing.JTextField();
        txtTenlop = new javax.swing.JTextField();
        txtGVCN = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        cboKhoahoc = new javax.swing.JComboBox<>();
        cboNganh = new javax.swing.JComboBox<>();
        hientoanbo = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnKhong = new javax.swing.JButton();
        btnNhapmoi = new javax.swing.JButton();
        lblThongbao = new javax.swing.JLabel();

        btnGhi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnGhi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Save as.png"))); // NOI18N
        btnGhi.setText("Ghi");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Chọn Khóa:");

        cboKhoa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboKhoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboKhoa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboKhoaItemStateChanged(evt);
            }
        });
        cboKhoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboKhoaMouseClicked(evt);
            }
        });
        cboKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboKhoaActionPerformed(evt);
            }
        });

        tbldulieu.setBackground(new java.awt.Color(255, 102, 51));
        tbldulieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbldulieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldulieuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbldulieu);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Mã lớp:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Tên lớp:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Khóa học :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Ngành:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("GVCN:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("SDT:");

        txtMalop.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtTenlop.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtGVCN.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtGVCN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtGVCNFocusLost(evt);
            }
        });

        txtSDT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSDT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSDTFocusLost(evt);
            }
        });

        cboKhoahoc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboKhoahoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboNganh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboNganh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(5, 5, 5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6))
                                .addGap(32, 32, 32)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMalop, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtGVCN)
                                .addComponent(txtTenlop)
                                .addComponent(txtSDT)
                                .addComponent(cboKhoahoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cboNganh, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMalop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenlop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboKhoahoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cboNganh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtGVCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        hientoanbo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hientoanbo.setText("Hiện toàn bộ ");
        hientoanbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hientoanboActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("QUẢN LÝ DANH MỤC LỚP");

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        btnThem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Add.png"))); // NOI18N
        btnThem.setText("Thêm ");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Edit.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnKhong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnKhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Stop.png"))); // NOI18N
        btnKhong.setText("Đóng chương trình");
        btnKhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhongActionPerformed(evt);
            }
        });

        btnNhapmoi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnNhapmoi.setText("Nhập mới");
        btnNhapmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapmoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(btnThem))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(98, 98, 98)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnNhapmoi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(btnSua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnKhong)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoa)
                    .addComponent(btnNhapmoi))
                .addGap(26, 26, 26)
                .addComponent(btnKhong)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        lblThongbao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblThongbao.setText("thông báo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jLabel8)
                                .addGap(0, 410, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cboKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(hientoanbo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblThongbao)
                                .addGap(151, 151, 151))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(cboKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(hientoanbo))
                            .addComponent(lblThongbao, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cboKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboKhoaActionPerformed

    }//GEN-LAST:event_cboKhoaActionPerformed

    private void tbldulieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldulieuMouseClicked
        int row = tbldulieu.getSelectedRow();

        if (row >= 0) {
            txtMalop.setText(tbldulieu.getValueAt(row, 0).toString());
            cboKhoahoc.setSelectedItem(tbldulieu.getValueAt(row, 1).toString());
            cboNganh.setSelectedItem(tbldulieu.getValueAt(row, 2).toString());
            txtTenlop.setText(tbldulieu.getValueAt(row, 3).toString());
            txtGVCN.setText(tbldulieu.getValueAt(row, 4).toString());
            txtSDT.setText(tbldulieu.getValueAt(row, 5).toString());
        }

    }//GEN-LAST:event_tbldulieuMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        txtMalop.setEnabled(true);

//        StringBuilder sb=new StringBuilder();
//        if(txtMalop.getText().equals("")){
//            sb.append("cần nhập mã lớp");
//            txtMalop.setBackground(Color.red);
//            txtMalop.requestFocus();
//        }
//        else{
//            txtMalop.setBackground(Color.white);
//        }
//        if(sb.length()>0){
//            JOptionPane.showMessageDialog(this, sb.toString());
//            return;
//        }
        if (ktTrungThem(txtMalop.getText()) == true) {
            JOptionPane.showMessageDialog(this, "trùng mã thêm");
            return;
        }
        if (txtTenlop.getText().equals("") || txtMalop.getText().equals("") || txtGVCN.getText().equals("") || txtSDT.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "cần nhập thông tin đầy đủ ");
            return;
        } else {
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String url = "jdbc:sqlserver://localhost:1433;databaseName=quanlysinhvien";
                String username = "sa";
                String password = "123456789";

                Connection con = DriverManager.getConnection(url, username, password);
                String sql = "insert into lop(malop,makhoa,manganh,tenlop,gvcn,sdt) values (?,?,?,?,?,?)";//
                PreparedStatement ps = con.prepareStatement(sql);

                ps.setString(1, txtMalop.getText());
                ps.setString(2, (String) this.cboKhoahoc.getSelectedItem());
                ps.setString(3, (String) this.cboNganh.getSelectedItem());
                ps.setString(4, txtTenlop.getText());
                ps.setString(5, txtGVCN.getText());
                ps.setString(6, txtSDT.getText());

                ps.executeUpdate();//để thực hiện câu lệnh insert into và đưa dữ liệu vào trong cơ sở dữ liệu
                loadDuLieu();//hiện dữ liệu lại ở trong table
                JOptionPane.showMessageDialog(this, "thêm thành công ");
                ps.close();
                con.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        txtMalop.disable();
        if (JOptionPane.showConfirmDialog(this, "bạn có muốn cập nhật ko ") == JOptionPane.NO_OPTION) {
            return;
        }
        if (txtTenlop.getText().equals("") || txtMalop.getText().equals("") || txtGVCN.getText().equals("") || txtSDT.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa có thông tin để sửa");
            return;
        } else {
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String url = "jdbc:sqlserver://localhost:1433;databaseName=quanlysinhvien";
                String username = "sa";
                String password = "123456789";
                // sql = "update lop set malop=N'" + txtMaLop.Text + "', tenlop=N'" + txtTenLop.Text
                //   + "',makhoa=N'" + cboKhoa.SelectedValue.ToString() + "', manganh=N'" + cboNganh.SelectedValue.ToString()
                //     + "',gvcn=N'" + txtGVCN.Text + "',sdt=N'" + txtSDT.Text + "' where malop=N'" + macu + "'";

                Connection con = DriverManager.getConnection(url, username, password);
                String sql = "UPDATE lop  SET malop=?, makhoa =?, manganh =?, tenlop =?, gvcn =?, sdt =?  where malop=?";
                PreparedStatement ps = con.prepareStatement(sql);

                ps.setString(1, txtMalop.getText());
                ps.setString(2, (String) this.cboKhoahoc.getSelectedItem());
                ps.setString(3, (String) this.cboNganh.getSelectedItem());
                ps.setString(4, txtTenlop.getText());
                ps.setString(5, txtGVCN.getText());
                ps.setString(6, txtSDT.getText());
                ps.setString(7, txtMalop.getText());

                ps.executeUpdate();//để thực hiện câu lệnh insert into ,...và đưa dữ liệu vào trong cơ sở dữ liệu
                loadDuLieu();//hiện dữ liệu lại ở trong table
                JOptionPane.showMessageDialog(this, "cập nhật thành công ");
                ps.close();
                con.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if (JOptionPane.showConfirmDialog(this, "bạn có muốn xóa dữ liệu ko ") == JOptionPane.NO_OPTION) {
            return;
        }
        if (txtTenlop.getText().equals("") || txtMalop.getText().equals("") || txtGVCN.getText().equals("") || txtSDT.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa có thông tin để xóa");
            return;
        } else {
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String url = "jdbc:sqlserver://localhost:1433;databaseName=quanlysinhvien";
                String username = "sa";
                String password = "123456789";

                Connection con = DriverManager.getConnection(url, username, password);
                String sql = "delete from lop where malop=?";
                PreparedStatement ps = con.prepareStatement(sql);

                ps.setString(1, txtMalop.getText());

                ps.executeUpdate();
                loadDuLieu();
                JOptionPane.showMessageDialog(this, "xóa thành công ");
                ps.close();
                con.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        txtGVCN.setText("");
        txtMalop.setText("");
        txtSDT.setText("");
        txtTenlop.setText("");
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnKhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhongActionPerformed

        System.exit(0);

    }//GEN-LAST:event_btnKhongActionPerformed

    private void cboKhoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboKhoaMouseClicked

    }//GEN-LAST:event_cboKhoaMouseClicked

    private void hientoanboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hientoanboActionPerformed
        loadDuLieu();
    }//GEN-LAST:event_hientoanboActionPerformed

    private void cboKhoaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboKhoaItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            try {
                int number;
                Vector row;
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String url = "jdbc:sqlserver://localhost:1433;databaseName=quanlysinhvien";
                String username = "sa";
                String password = "123456789";

                Connection con = DriverManager.getConnection(url, username, password);
                String sql = "select * from lop where makhoa= '" + cboKhoa.getSelectedItem() + "'";
                Statement ps = con.createStatement();
                ResultSet rs = ps.executeQuery(sql);
                ResultSetMetaData metadata = rs.getMetaData();
                number = metadata.getColumnCount();
                tblModel.setRowCount(0);
                while (rs.next()) {
                    row = new Vector();
                    for (int i = 1; i <= number; i++) {
                        row.addElement(rs.getString(i));
                    }
                    tblModel.addRow(row);
                    tbldulieu.setModel(tblModel);
                }
                ps.close();
                con.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_cboKhoaItemStateChanged

    private void txtSDTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSDTFocusLost
        if (this.isVisible()) {
            String sdt = txtSDT.getText();
            String reg = "^\\d{9}";
            if (sdt.length() > 0) {
                if (!sdt.matches(reg)) {//sdt sai định dạng
                    JOptionPane.showMessageDialog(this, "sai định dạng,phải nhập đủ 9 số ");
                    txtSDT.requestFocus();
                    txtSDT.setBackground(Color.red);
                } else {
                    txtSDT.setBackground(Color.white);
                }
            } else {
                JOptionPane.showMessageDialog(this, "sdt không được để trống");
            }
        }
    }//GEN-LAST:event_txtSDTFocusLost

    private void btnNhapmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapmoiActionPerformed
                // TODO add your handling code here:
        txtGVCN.setText("");
        txtMalop.setText("");
        txtTenlop.setText("");
        txtSDT.setText("");
        
    }//GEN-LAST:event_btnNhapmoiActionPerformed

    private void txtGVCNFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGVCNFocusLost
         if (this.isVisible()) {
            String sdt = txtGVCN.getText();
            String reg = "^\\w{6}$";
            if (sdt.length() > 0) {
                if (!sdt.matches(reg)) {//sdt sai định dạng
                    JOptionPane.showMessageDialog(this, "sai định dạng,phải nhập chữ");
                    txtGVCN.requestFocus();
                    txtGVCN.setBackground(Color.red);
                } else {
                    txtGVCN.setBackground(Color.white);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Tên giáo viên không được để trống");
            }
        }
    }//GEN-LAST:event_txtGVCNFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGhi;
    private javax.swing.JButton btnKhong;
    private javax.swing.JButton btnNhapmoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboKhoa;
    private javax.swing.JComboBox<String> cboKhoahoc;
    private javax.swing.JComboBox<String> cboNganh;
    private javax.swing.JButton hientoanbo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblThongbao;
    private javax.swing.JTable tbldulieu;
    private javax.swing.JTextField txtGVCN;
    private javax.swing.JTextField txtMalop;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenlop;
    // End of variables declaration//GEN-END:variables

    private void loadDuLieu() {
        tbldulieu.setDefaultEditor(Object.class, null); //không cho người dùng chỉnh sửa 
        
        
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=quanlysinhvien";
            String username = "sa";
            String password = "123456789";

            Connection con = DriverManager.getConnection(url, username, password);
            String sql = "select*from lop";
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();//trả về kết quả ResultSet
            tblModel.setRowCount(0);
            while (rs.next()) {
                String[] row = new String[]{
                    rs.getString("malop"), rs.getString("makhoa"), rs.getString("manganh"), rs.getString("tenlop"), rs.getString("gvcn"), rs.getString("sdt")
                };
                tblModel.addRow(row);
            }

            tblModel.fireTableDataChanged();//cập nhật dữ liệu trong bảng
            rs.close();
            ps.close();
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        lblThongbao.setText("Có " + tbldulieu.getRowCount() + " bản ghi.");
    }

    private void initTable() {
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(new String[]{"Mã Lớp", "Mã Khoa", "Mã Ngành", "Tên Lớp", "GVCN", "Số điện thoại"});
        tbldulieu.setModel(tblModel);//thiết lập model cho table
    }

    private void ComboBox() {
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String ConnectionUrl = "jdbc:sqlserver://localhost:1433;databaseName=quanlysinhvien";
            String username = "sa";
            String password = "123456789";
            Connection con = DriverManager.getConnection(ConnectionUrl, username, password);
            
            String sql = "select makhoa,manganh from lop group by makhoa,manganh";
            PreparedStatement pstmt = con.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            cboKhoahoc.removeAllItems();
            cboNganh.removeAllItems();
            cboKhoa.removeAllItems();
            while (rs.next()) {
                cboKhoahoc.addItem(rs.getString("makhoa"));
                cboNganh.addItem(rs.getString("manganh"));
                cboKhoa.addItem(rs.getString("makhoa"));

            }
            rs.close();
            pstmt.close();
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}
